# Generated by Django 4.0.1 on 2022-03-01 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_site', '0003_offer_receiver_name_offer_sender_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='p_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
