# Generated by Django 4.0.1 on 2022-03-01 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_site', '0004_offer_p_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='property_name',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
