# Generated by Django 4.0.1 on 2022-03-03 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_site', '0006_offer_accepted'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='receiver_num',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='offer',
            name='sender_num',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=10),
        ),
    ]
