# Generated by Django 4.0.1 on 2022-03-03 19:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_site', '0007_offer_receiver_num_offer_sender_num'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
