# Generated by Django 4.0.1 on 2022-03-04 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_site', '0009_siteuser_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='picture',
            field=models.FileField(blank=True, default='property_img/default_pic.jpg', upload_to='property_img'),
        ),
    ]
